# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arca < Formula
  desc "CLI for the Arca platform"
  homepage "https://arcaos.io"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arcaresearch/arca-cli/releases/download/v0.0.11/arca_0.0.11_darwin_amd64.tar.gz"
      sha256 "6bc1400a731468377b6029d0f141bbd9e2799ae50899e602827e7b3f7ea9e52c"

      define_method(:install) do
        bin.install "arca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arcaresearch/arca-cli/releases/download/v0.0.11/arca_0.0.11_darwin_arm64.tar.gz"
      sha256 "17d7055e823cb41413e22bc25f938407ed04f8da4d3d9951477ae881191faf7f"

      define_method(:install) do
        bin.install "arca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcaresearch/arca-cli/releases/download/v0.0.11/arca_0.0.11_linux_amd64.tar.gz"
      sha256 "505b930eb6d2388c1d6b6247ed788133dd50a5526e0dad4b36875466437471c8"
      define_method(:install) do
        bin.install "arca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcaresearch/arca-cli/releases/download/v0.0.11/arca_0.0.11_linux_arm64.tar.gz"
      sha256 "bee0a46608626577a0e9685807e37bf5b8c948f3ba0a7d944037d43c6bcf1809"
      define_method(:install) do
        bin.install "arca"
      end
    end
  end

  test do
    system "#{bin}/arca", "--help"
  end
end
