# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arca < Formula
  desc "CLI for the Arca platform"
  homepage "https://arcaos.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arcaresearch/arca-cli/releases/download/v0.1.0/arca_0.1.0_darwin_amd64.tar.gz"
      sha256 "973689247c1543eb19073c633adae16434ea5fe39c07a8933ff5922b81ba36e8"

      define_method(:install) do
        bin.install "arca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arcaresearch/arca-cli/releases/download/v0.1.0/arca_0.1.0_darwin_arm64.tar.gz"
      sha256 "e1ac5d686d5dd8d679bfef3640dc683c4ab2ed314bdfbdc1fa5dd511daa41408"

      define_method(:install) do
        bin.install "arca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcaresearch/arca-cli/releases/download/v0.1.0/arca_0.1.0_linux_amd64.tar.gz"
      sha256 "2e2be56779e97f2893dd9cc07baaea2bd034954e36a6636b75000700c4aa0eb2"
      define_method(:install) do
        bin.install "arca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcaresearch/arca-cli/releases/download/v0.1.0/arca_0.1.0_linux_arm64.tar.gz"
      sha256 "ccb273123d492cfeaa3a331b1331927491c0f88307ed96996470817cbcf67812"
      define_method(:install) do
        bin.install "arca"
      end
    end
  end

  test do
    system "#{bin}/arca", "--help"
  end
end
